version: "3.8"
services:
  envoy:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    ports:
      - "8080:8080"

  app:
    build:
      context: .
      dockerfile: "${PWD}/../chat-app-server/docker/Dockerfile"
    container_name: "server"
    tty: true
    volumes:
      - "${PWD}/../chat-app-server:/var/app/"
    ports:
      - "9000:9000"

  client:
    build:
      context: .
      dockerfile: "${PWD}/../chat-app-client/docker/Dockerfile"
    tty: true
    volumes:
      -  "${PWD}/../chat-app-client:/var/www/app"
    ports:
      - "3000:3000"